parser: typescript-eslint/parser
extends:
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2020
  sourceType: module
# env:
#   es6: true
#   browser: true
#   node: true
#   jasmine: true
#   jest: true
rules:
  # the rules
